# Gradle properties
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric properties - check https://fabricmc.net/develop/ for updates
minecraft_version=1.21.11
loader_version=0.19.5
loom_version=1.17.20

# Mod properties
version=1.4.0
group=com.kcb.serverpass

# Dependencies
fabric_api_version=0.141.1+1.21.11
